# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x03\x61pi\"\x06\n\x04Void\"\x1a\n\x0cMinerRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\"\xc5\x01\n\tMinerInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07pending\x18\x03 \x01(\x03\x12\x17\n\x0fhistoricalShare\x18\x04 \x01(\x01\x12\x19\n\x11\x65\x66\x66\x65\x63tiveCapacity\x18\x05 \x01(\x01\x12\x10\n\x08\x64\x65\x61\x64line\x18\x06 \x01(\x04\x12\x1d\n\x15lastActiveBlockHeight\x18\x07 \x01(\x04\x12\r\n\x05nConf\x18\x08 \x01(\x05\x12\x14\n\x0cpayoutDetail\x18\t \x01(\t\"S\n\rPoolStatsInfo\x12\x12\n\nminerCount\x18\x01 \x01(\x05\x12\x1d\n\x15\x65\x66\x66\x65\x63tivePoolCapacity\x18\x02 \x01(\x01\x12\x0f\n\x07netDiff\x18\x03 \x01(\x01\"\x9e\x01\n\tBlockInfo\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x12\n\nbaseTarget\x18\x02 \x01(\x04\x12\r\n\x05scoop\x18\x03 \x01(\r\x12\x1b\n\x13generationSignature\x18\x04 \x01(\t\x12\x0f\n\x07minerID\x18\x05 \x01(\x04\x12\r\n\x05miner\x18\x06 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x07 \x01(\x04\x12\x0f\n\x07\x63reated\x18\x08 \x01(\t2\x9c\x01\n\x03\x41pi\x12\x33\n\x0cGetMinerInfo\x12\x11.api.MinerRequest\x1a\x0e.api.MinerInfo\"\x00\x12\x33\n\x10GetPoolStatsInfo\x12\t.api.Void\x1a\x12.api.PoolStatsInfo\"\x00\x12+\n\x0cGetBlockInfo\x12\t.api.Void\x1a\x0e.api.BlockInfo\"\x00\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='api.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=24,
)


_MINERREQUEST = _descriptor.Descriptor(
  name='MinerRequest',
  full_name='api.MinerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='api.MinerRequest.ID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=52,
)


_MINERINFO = _descriptor.Descriptor(
  name='MinerInfo',
  full_name='api.MinerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='api.MinerInfo.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='api.MinerInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pending', full_name='api.MinerInfo.pending', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='historicalShare', full_name='api.MinerInfo.historicalShare', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effectiveCapacity', full_name='api.MinerInfo.effectiveCapacity', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='api.MinerInfo.deadline', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastActiveBlockHeight', full_name='api.MinerInfo.lastActiveBlockHeight', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nConf', full_name='api.MinerInfo.nConf', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payoutDetail', full_name='api.MinerInfo.payoutDetail', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=252,
)


_POOLSTATSINFO = _descriptor.Descriptor(
  name='PoolStatsInfo',
  full_name='api.PoolStatsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minerCount', full_name='api.PoolStatsInfo.minerCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effectivePoolCapacity', full_name='api.PoolStatsInfo.effectivePoolCapacity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='netDiff', full_name='api.PoolStatsInfo.netDiff', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=337,
)


_BLOCKINFO = _descriptor.Descriptor(
  name='BlockInfo',
  full_name='api.BlockInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='api.BlockInfo.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='baseTarget', full_name='api.BlockInfo.baseTarget', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scoop', full_name='api.BlockInfo.scoop', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generationSignature', full_name='api.BlockInfo.generationSignature', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minerID', full_name='api.BlockInfo.minerID', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='miner', full_name='api.BlockInfo.miner', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='api.BlockInfo.deadline', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='api.BlockInfo.created', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=498,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['MinerRequest'] = _MINERREQUEST
DESCRIPTOR.message_types_by_name['MinerInfo'] = _MINERINFO
DESCRIPTOR.message_types_by_name['PoolStatsInfo'] = _POOLSTATSINFO
DESCRIPTOR.message_types_by_name['BlockInfo'] = _BLOCKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Void)
  ))
_sym_db.RegisterMessage(Void)

MinerRequest = _reflection.GeneratedProtocolMessageType('MinerRequest', (_message.Message,), dict(
  DESCRIPTOR = _MINERREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.MinerRequest)
  ))
_sym_db.RegisterMessage(MinerRequest)

MinerInfo = _reflection.GeneratedProtocolMessageType('MinerInfo', (_message.Message,), dict(
  DESCRIPTOR = _MINERINFO,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.MinerInfo)
  ))
_sym_db.RegisterMessage(MinerInfo)

PoolStatsInfo = _reflection.GeneratedProtocolMessageType('PoolStatsInfo', (_message.Message,), dict(
  DESCRIPTOR = _POOLSTATSINFO,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.PoolStatsInfo)
  ))
_sym_db.RegisterMessage(PoolStatsInfo)

BlockInfo = _reflection.GeneratedProtocolMessageType('BlockInfo', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKINFO,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.BlockInfo)
  ))
_sym_db.RegisterMessage(BlockInfo)



_API = _descriptor.ServiceDescriptor(
  name='Api',
  full_name='api.Api',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=501,
  serialized_end=657,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMinerInfo',
    full_name='api.Api.GetMinerInfo',
    index=0,
    containing_service=None,
    input_type=_MINERREQUEST,
    output_type=_MINERINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPoolStatsInfo',
    full_name='api.Api.GetPoolStatsInfo',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_POOLSTATSINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlockInfo',
    full_name='api.Api.GetBlockInfo',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_BLOCKINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['Api'] = _API

# @@protoc_insertion_point(module_scope)
